name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  AWS_REGION: 'ap-northeast-2'
  ECR_REPOSITORY: 'sgs-frontend'

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1
    
    - name: Get version
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "::set-output name=version::$VERSION"

    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION : ${{ env.AWS_REGION }}
        
    - name: Build and Push Docker Image
      id: build_push_image
      run: |
        docker build -t ${{ steps.login_ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.version }} .
        docker push ${{ steps.login_ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.version }}
        echo "::set-output name=image::${{ steps.login_ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.version }}"

    - name: Set up SSH
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: ${{ secrets.EC2_IP }}
        username: ec2-user
        script: |
          if [ "$(docker ps -qa -f name=${{ env.ECR_REPOSITORY }})" ]; then
              docker rm -f ${{ env.ECR_REPOSITORY }}
            fi
            
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.login_ecr.outputs.registry }} 
            docker pull ${{ steps.login_ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.image.outputs.version }}
            docker run -d --name ${{ env.ECR_REPOSITORY }} -p 3000:3000 ${{ steps.build_push_image.outputs.image }}
